model_cfg:
    type: PartVQVAEs
    network_cfg:
        type: SepVQVAE
        up_half:
            levels: 1
            downs_t: [ 2, ]
            strides_t: [ 2, ]
            emb_width: 512
            l_bins: 512
            l_mu: 0.99
            commit: 0.02
            hvqvae_multipliers: [ 1, ]
            width: 512
            depth: 3
            m_conv: 1.0
            dilation_growth_rate: 3
            sample_length: 240
            use_bottleneck: True
            joint_channel: 3
            rot_joint_channel: 9
            pos_channel: 48
            rot_channel: 144
            vel: 1
            acc: 1
            vqvae_reverse_decoder_dilation: True
        down_half:
            levels: 1
            downs_t: [ 2, ]
            strides_t: [ 2, ]
            emb_width: 512
            l_bins: 512
            l_mu: 0.99
            commit: 0.02
            hvqvae_multipliers: [ 1, ]
            width: 512
            depth: 3
            m_conv: 1.0
            dilation_growth_rate: 3
            sample_length: 240
            use_bottleneck: True
            joint_channel: 3
            rot_joint_channel: 9
            pos_channel: 27
            rot_channel: 81
            vel: 1
            acc: 1
            vqvae_reverse_decoder_dilation: True
        lhand:
            levels: 1
            downs_t: [ 2, ]
            strides_t: [ 2, ]
            emb_width: 512
            l_bins: 512
            l_mu: 0.99
            commit: 0.02
            hvqvae_multipliers: [ 1, ]
            width: 512
            depth: 3
            m_conv: 1.0
            dilation_growth_rate: 3
            sample_length: 240
            use_bottleneck: True
            joint_channel: 3
            rot_joint_channel: 9
            pos_channel: 45
            rot_channel: 135
            vel: 1
            acc: 1
            vqvae_reverse_decoder_dilation: True
        rhand:
            levels: 1
            downs_t: [ 2, ]
            strides_t: [ 2, ]
            emb_width: 512
            l_bins: 512
            l_mu: 0.99
            commit: 0.02
            hvqvae_multipliers: [ 1, ]
            width: 512
            depth: 3
            m_conv: 1.0
            dilation_growth_rate: 3
            sample_length: 240
            use_bottleneck: True
            joint_channel: 3
            rot_joint_channel: 9
            pos_channel: 45
            rot_channel: 135
            vel: 1
            acc: 1
            vqvae_reverse_decoder_dilation: True
        joint_channel: 3
        rot_joint_channel: 9
        pos_channel: 165
        rot_channel: 495
        emb_width: 512
        downs_t: [ 2, ]
        strides_t: [ 2, ]
        levels: 1
        multipliers: [ 1, ]
        width: 512
        depth: 3
        m_conv: 1.0
        dilation_growth_rate: 3
        vqvae_reverse_decoder_dilation: True
        commit: 0.02
        vel: 1
        acc: 1
runner_cfg:
    type: LowLevelMoPredRunner
    epochs: 500
    ep_iter: 1000
    eval_ep: 50
    save_ep: 50
    log_interval: 10
    record_interval: 10
    optimizer_cfg:
        type: Adam
        lr: 0.00003
        betas: [0.5, 0.999]
        weight_decay: 0
    scheduler_cfg:
        type: MultiStepLR
        milestones: [100000, 200000]
        gamma: 0.1
    evaluator_cfg:
        type: PartFusionVQEvaluator
        metric_names:
            - mpjpe
            - mpjve
